language: swift
osx_image: xcode7.3
xcode_project: GraphQL.xcodeproj # path to your xcodeproj folder
xcode_scheme: GraphQLTests
env:
  global:
    - FRAMEWORK_NAME=GraphQL
before_install:
  - brew update
  - brew install carthage
before_script:
  - carthage bootstrap --verbose --no-use-binaries
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
